### ISSUE TITLE
Does the original author know about this project?

### ISSUE THREAD

**Issue by FranklinChen** [Oric4ever/Turbo-Modula-2-Reloaded#2]
Does the original author, Martin Odersky, know about this project? :-)

See https://skillsmatterblog.wordpress.com/2014/12/08/while-its-compiling-skills-matter-interviews-martin-odersky/
 and https://groups.google.com/g/comp.lang.modula2/c/Ruy9g8aBmF0/m/ItZdWWpqCMkJ

**Comment by Oric4ever** [comment]
I exchanged mails with Martin Odersky two years ago, he was surprised (and happy I guess) that someone could still be interested in his old compiler. At that time he had still hope to have a copy of the original sources on 5"1/4 in his parents' attic... Unfortunately he didn't find them, so I embarked on disassembling/decompiling the whole thing...

Best regards,

Fabrice
