### ISSUE TITLE
compiler files missing?

### ISSUE THREAD

**Issue by mbmcgaw** [Oric4ever/Turbo-Modula-2-Reloaded#3]
VERY interesting project!  I have spent considerable time on the original Lilith system and compiler, and have had an interest in finding the sources to the later Wirth single pass compiler (with the M-code code generation capability), but have not been successful in this.  The turboM2 compiler looks to be able to fill the bill, here, so....  a couple of questions:

1. I am inquiring as to the files EXPRESS.MOD, PASS1.MOD and STATEMEN.MOD.  The compiled forms of these appear in the Compiler.Dir folder, but the sources do not exist anywhere in the source tree (at least I could not find them).

2. Does the author know if the object format is that used by the Lilith system (original Modula-2 compiler and OS)?  I have a working set of sources that can be used to compile, link and run M-code programs, and I really like the simplicity of this Turbo M2 compiler, and would like to look at this for replacing the multipass compiler in Lilith.

Thanks!

**Comment by Oric4ever** [comment]
Hello there, please note I have no way to contact you except writing a private answer in this place, which is not the intended role of GitHub's Issues... 

On 14/01/2021 16:38, mbmcgaw wrote:
>
> VERY interesting project! I have spent considerable time on the original Lilith system and compiler, and have had an interest in finding the sources to the later Wirth single pass compiler (with the M-code code generation capability), but have not been successful in this.

Hello there, I would also love to have the sources of Pr. Wirth's single pass compiler, it would let me understand if the TurboM2 compiler is a derived work...
>
> The turboM2 compiler looks to be able to fill the bill, here, so.... a couple of questions:
>
>     I am inquiring as to the files EXPRESS.MOD, PASS1.MOD and STATEMEN.MOD. The compiled forms of these appear in the Compiler.Dir folder, but the sources do not exist anywhere in the source tree (at least I could not find them).
>
yeap, because I don't have them. There were no sources at all in TurboM2...

I'm decompiling every module one after the other, by hand, with the objective to provide the sources...

Current status:

- library : 100 % complete. I've just finished decompiling every module of the library, the resulting sources are satisfying (I haven't put them all on the git project)...
- editor : 100 % complete, but the sources are not all that readable.
- compiler : EXPRESSION, PASS1 and STATEMENT modules : 0% complete. ERRORS, CODEGEN, COMPILER: 100% complete, but CODEGEN is not very readable. I'm currently decompiling the SCANNER and SYMTAB modules, readability will vary...

Hand decompilation speed : 100 to 200 bytes per hour... Biggest difficulty is to guess the types of the data structures, understand all the code to guess intelligible identifiers...


>
>     Does the author know if the object format is that used by the Lilith system (original Modula-2 compiler and OS)?
>

The bytecode specification is not the one used by the Lilith system : a lot of bytecodes are identical (but not numbered the same), some bytecodes are missing, and new bytecodes have been added by the TurboM2 designers...
>
>     I have a working set of sources that can be used to compile, link and run M-code programs, and I really like the simplicity of this Turbo M2 compiler, and would like to look at this for replacing the multipass compiler in Lilith.
>
Mhhh... Even if your sources are those of a 4 pass compiler, I am interested in them, it could help me understand the compiler code I am decompiling...

Best regards,

Fabrice

**Comment by mbmcgaw** [comment]
Hello Fabrice:

I would be very pleased to send you my port of the Lilith multipass M2 compiler, a linker and an interpreter. The compiler was ported to StonyBrook (now ADW?) M2, 16 bit target, and runs under DOSBox.
I have ported the interpreter to also run on Oberon, V4 (Linz).

To understand this compiler, though, you really need some of the theses surrounding this work, and I have pdfs of all of this as well (some I had to go directly to ETH Bibliotek to obtain, as the were old enough to only exist in paper form), 
and I would be pleased to send these as well. 

You may also be interested in MacMeth, a single pass M2 compiler written by Wirth and later, others, targeting 68000/MAC. I think the front end of this must be directly related to the single pass compiler Wirth originally wrote, and which I
would bet bears a close resemblance to Turbo M2. I have sources for MacMeth M2, but no one knows where the sources for single pass M2 targeting M-Code is any longer. Certainly Wirth no longer has these, as I have asked about them, as I
know him well enough that he pays attention to my inquiries.

Finally, the Russian Kronos project was based on Lilith, and extended M-Code to 32-bits. The authors wrote a single pass compiler for this, and the sources are around. It may also be of interest, although not to trace the work directly, I think.

I can put all this together and send you a google drive link- but I do not want to post that on Github, and will need to find some way to send this privately. What do you suggest?

M
     On Saturday, January 16, 2021, 03:30:50 AM EST, Oric4ever <notifications@github.com> wrote:  
 
 


Hello there, please note I have no way to contact you except writing a private answer in this place, which is not the intended role of GitHub's Issues...

On 14/01/2021 16:38, mbmcgaw wrote:


VERY interesting project! I have spent considerable time on the original Lilith system and compiler, and have had an interest in finding the sources to the later Wirth single pass compiler (with the M-code code generation capability), but have not been successful in this.


Hello there, I would also love to have the sources of Pr. Wirth's single pass compiler, it would let me understand if the TurboM2 compiler is a derived work...


The turboM2 compiler looks to be able to fill the bill, here, so.... a couple of questions:
I am inquiring as to the files EXPRESS.MOD, PASS1.MOD and STATEMEN.MOD. The compiled forms of these appear in the Compiler.Dir folder, but the sources do not exist anywhere in the source tree (at least I could not find them).

yeap, because I don't have them. There were no sources at all in TurboM2...

I'm decompiling every module one after the other, by hand, with the objective to provide the sources...

Current status:
   
   - library : 100 % complete. I've just finished decompiling every module of the library, the resulting sources are satisfying (I haven't put them all on the git project)...
   - editor : 100 % complete, but the sources are not all that readable.
   - compiler : EXPRESSION, PASS1 and STATEMENT modules : 0% complete. ERRORS, CODEGEN, COMPILER: 100% complete, but CODEGEN is not very readable. I'm currently decompiling the SCANNER and SYMTAB modules, readability will vary...

Hand decompilation speed : 100 to 200 bytes per hour... Biggest difficulty is to guess the types of the data structures, understand all the code to guess intelligible identifiers...

Does the author know if the object format is that used by the Lilith system (original Modula-2 compiler and OS)?

The bytecode specification is not the one used by the Lilith system : a lot of bytecodes are identical (but not numbered the same), some bytecodes are missing, and new bytecodes have been added by the TurboM2 designers...

I have a working set of sources that can be used to compile, link and run M-code programs, and I really like the simplicity of this Turbo M2 compiler, and would like to look at this for replacing the multipass compiler in Lilith.

Mhhh... Even if your sources are those of a 4 pass compiler, I am interested in them, it could help me understand the compiler code I am decompiling...

Best regards,

Fabrice

**Comment by Oric4ever** [comment]
Wow, all this sounds so interesting... I've now finished to decompile the SCANNER module by hand, but the result currently is very poor (what I mean is the resulting source compiles to an object module byte-to-byte-identical to the original one, but I haven't guessed how to name most of the identifiers, and the data structures are not very well typed either), so your files would be much appreciated...

My email address should have been revealed with this answer, could we exchange privately by mail ?

Best regards,

Fabrice

**Comment by mbmcgaw** [comment]
Hello Fabrice:

Github seems quite inscrutable in its handling of email addresses in these exchanges.

Here is what I see on an incoming email:

Oric4ever <notifications@github.com>
To: Oric4ever/Turbo-Modula-2-Reloaded <turbo-modula-2-reloaded@noreply.github.com>
Cc: mbmcgaw <mcgawma@yahoo.com>,Author <author@noreply.github.com>

You will notice that your private email address is not disclosed. Moreover, when I did a reply to your email, this is the address to which my email is being sent:

"Oric4ever/Turbo-Modula-2-Reloaded" <reply@reply.github.com>

So, yes, we should exchange private addresses: as you can see from the above, mine is: mcgawma@yahoo.com.

I will begin assembling this material, so that I can create the google drive link for your use, and when I receive your email address, I will respond with a short email that contains this link.

Thanks very much! 

Mike
     On Sunday, January 17, 2021, 07:08:09 AM EST, Oric4ever <notifications@github.com> wrote:  
 
 


Wow, all this sounds so interesting... I've now finished to decompile the SCANNER module by hand, but the result currently is very poor (what I mean is the resulting source compiles to an object module byte-to-byte-identical to the original one, but I haven't guessed how to name most of the identifiers, and the data structures are not very well typed either), so your files would be much appreciated...

My email address should have been revealed with this answer, could we exchange privately by mail ?

Best regards,

Fabrice
